Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 5432, host: 5432

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y postgresql postgresql-contrib
    sudo -u postgres psql -c "CREATE USER vagrant WITH PASSWORD 'vagrant';"
    sudo -u postgres psql -c "CREATE DATABASE prisma_db;"
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE prisma_db TO vagrant;"
    sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/10/main/postgresql.conf
    echo "host all all all md5" | sudo tee -a /etc/postgresql/10/main/pg_hba.conf
    sudo systemctl restart postgresql
  SHELL
end
